### ISSUE TITLE
style.css

### ISSUE THREAD

**Issue by jiyeong1004** [jiyeong1004/Animated_Background#4]
https://www.youtube.com/watch?v=_eGgLivujtc&t=75s

**Comment by Shubham56-droid** [comment]
i will do it for you please assign this  issue to me

**Comment by jiyeong1004** [comment]
> i will do it for you please assign this issue to me

This project is just for study, so that's ok. Thank you~!
If you are interested, take a look at the lecture ! !
(YouTube Lecture Link : https://www.youtube.com/watch?v=_eGgLivujtc&t=75s)
